name: Build Stock Dashboard

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
      - 20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]*

jobs:
  build-and-push:
    uses: ./.github/workflows/dockerfiles.yaml
    with:
      image: touhou09/stockprocessing
      path: ./
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}