name: Build anything

on:
  workflow_call:
    inputs:
      build_group:
        description: 'Github runners tag'
        type: string
        required: false
        default: ubuntu-22.04
      image:
        description: 'Docker image name'
        type: string
        required: true
      path:
        description: 'Path to Dockerfile'
        type: string
        required: true
      build_timeout:
        description: 'Build timeout minutes'
        type: number
        required: false
        default: 3600
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ${{ inputs.build_group }}
    outputs:
      image_version: ${{ steps.meta.outputs.version }}
      image_id: ${{ steps.build_push.outputs.imageid }}
      commit_message: ${{ steps.commit_info.outputs.message }}
      commit_hash: ${{ steps.commit_info.outputs.hash }}
      author_name: ${{ steps.commit_info.outputs.author_name }}
      author_email: ${{ steps.commit_info.outputs.author_email }}
      timeout-minutes: ${{ inputs.build_timeout }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          flavor: |
            latest=false                                   # [수정] latest 태그 중지
          tags: |
            type=raw,event=tag,value={{tag}}              # [수정] Git 태그 그대로 사용
            type=match,event=tag,pattern=v\d+.\d+.\d+.*
            type=match,event=tag,pattern=20[0-9][0-9]-[0-1][0-9]-[0-3][0-9].*
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get head commit information
        id: commit_info
        run: |
          echo "message=$(git log -n 1 --format=%B HEAD | head -n 1)" >> $GITHUB_OUTPUT
          echo "hash=$(git log -n 1 --format=%H | head -n 1)" >> $GITHUB_OUTPUT
          echo "author_name=$(git log -n 1 --format=%an | head -n 1)" >> $GITHUB_OUTPUT
          echo "author_email=$(git log -n 1 --format=%ae | head -n 1)" >> $GITHUB_OUTPUT
      - name: Build and push
        id: build_push
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.path }}
          platforms: linux/amd64
          file: ${{ inputs.path }}/dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max