name: Build anything

on:
  workflow_call:
    inputs:
      # [수정] build_group 입력 제거
      image:
        description: 'Docker image name'
        type: string
        required: true
      path:
        description: 'Path to Docker context (folder containing Dockerfile)'
        type: string
        required: true
      # [수정] build_timeout 입력 제거(잡 옵션으로 통일)
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest              # [수정] 러너 그룹 대신 GitHub 호스티드 기본값
    timeout-minutes: 60                 # [수정] 입력 대신 고정(필요시 숫자만 조정)
    outputs:
      image_version: ${{ steps.meta.outputs.version }}
      image_id: ${{ steps.build_push.outputs.imageid }}
      commit_message: ${{ steps.commit_info.outputs.message }}
      commit_hash: ${{ steps.commit_info.outputs.hash }}
      author_name: ${{ steps.commit_info.outputs.author_name }}
      author_email: ${{ steps.commit_info.outputs.author_email }}
      # [수정] timeout-minutes 출력 제거

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          flavor: |
            latest=true
          tags: |
            type=raw,value={{date 'YYYYMMDD.HHmmss' tz='Asia/Seoul'}}-{{sha}},enable={{is_default_branch}}
            type=match,event=tag,pattern=v\d+.\d+.\d+.*
            type=match,event=tag,pattern=20[0-9][0-9]-[0-1][0-9]-[0-3][0-9].*

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.path }}
          # [수정] file 옵션 제거 → Dockerfile 자동 탐지(Dockerfile/dockerfile)
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get head commit information
        id: commit_info
        run: |
          echo "message=$(git log -n 1 --format=%B HEAD | head -n 1)" >> $GITHUB_OUTPUT
          echo "hash=$(git log -n 1 --format=%H | head -n 1)" >> $GITHUB_OUTPUT
          echo "author_name=$(git log -n 1 --format=%an | head -n 1)" >> $GITHUB_OUTPUT
          echo "author_email=$(git log -n 1 --format=%ae | head -n 1)" >> $GITHUB_OUTPUT
